// variable contiene llamado a la funcion de las librerias de sweet alert el onclick="swal2()" activa el evento
var swal1 = () => swal("Un punto de acceso inalámbrico (en inglés: wireless access point, conocido por las siglas WAP o AP), en una red de computadoras, es un dispositivo de red que interconecta equipos de comunicación inalámbricos, para formar una red inalámbrica que interconecta dispositivos móviles o tarjetas de red inalámbricas");

var swal2 = () => swal("La tecnología Wi-Fi ha mejorado muchísimo en los últimos años pero no ofrece una solución integral para todos los tipos de usuarios de red, sobretodo en lo relativo a las redes profesionales. En oficinas grandes con un tráfico intenso se suelen utilizar puntos de acceso Wi-Fi mientras que en oficinas más pequeñas, con menos usuarios, es probable que se utilicen routers Wi-Fi y extensores de red. A continuación, vamos a comparar las distintas funciones de cada opción para evaluar cuál es la mejor solución Wi-Fi para usted.");

var swal3 = () => swal("Un punto de acceso es un dispositivo que crea una red de área local inalámbrica (WLAN), normalmente en una oficina o un edificio de grandes dimensiones. Un punto de acceso se conecta a un router, switch o hub por un cable Ethernet y proyecta una señal Wi-Fi en un área designada. Por ejemplo, si desea habilitar el acceso Wi-Fi en la zona del vestíbulo de su empresa pero no tiene un router que pueda cubrirla puede instalar un punto de acceso cerca de la recepción y conectarlo con un cable por el techo a la sala del servidor.");

var swal4 = () => swal("Como su propio nombre indica un extensor de red incrementa el alcance de una red Wi-Fi ya existente Como los extensores de red se conectan inalámbricamente a los routers Wi-Fi es necesario emplazarlos allí donde la señal del router Wi-Fi sea fuerte y no donde esté debilitada. Por ejemplo, si su router se ubica en el sótano de un edificio de dos plantas instalar un extensor de red en la primera (donde la cobertura todavía es robusta) eliminará las posibles zonas sin cobertura en la segunda planta.");

var swal5 = () => swal("Aunque los extensores de red son extremadamente útiles para redes Wi-Fi domésticas  no son lo suficientemente eficientes para las redes profesionales modernas. Esto es porque solo pueden dar servicio a un número limitado de dispositivos al mismo tiempo, normalmente a 20 como máximo. Los puntos de acceso, por otra parte, pueden operar unas 60 conexiones simultáneas por cabeza. Al instalar puntos de acceso en toda la extensión de la oficina los usuarios podrán moverse con total libertad de una sala de juntas a otra sin sufrir interrupciones en el servicio. Conforme se desplazan por el edificio sus dispositivos irán conmutando sin complicaciones de un punto al siguiente sin interrumpir la conexión. El usuario ni siquiera se dará cuenta de los cambios.");

var swal6 = () => swal("Si tanto sus empleados comos sus invitados se conectan a la red usando sus ordenadores de sobremesa, portátiles, smartphones y tabletas el cupo máximo de 20 dispositivos conectados se llenará con rapidez. Dando la posibilidad de manejar hasta 60 conexiones simultáneas los puntos de acceso le ofrecen la libertad de escalar el número de dispositivos que la red puede admitir.");

var swal7 = () => swal("WiFi gratuito. Generalmente los hotspot de WiFi gratuito suelen ir asociados a algún servicio (ser cliente de un restaurante, estar alojado en un hotel, pertenecer a un centro…). Se llama de servicio porque realmente esa conexión no es totalmente gratuita, sino que el acceso a internet se permite a cambio de consumir un servicio concreto. Otras veces se pide el registro del usuario, pidiendo un email de contacto, un teléfono o incluso una tarjeta de crédito.");

var swal8 = () => swal(" WiFi portátil. Y otra forma de tener acceso es a través de WiFi portátil que se establece mediante un dispositivo que tiene Internet y lo comparte con otros que lo solicitan. El ejemplo más común que encontramos es pasar la conexión de nuestro teléfono móvil a una Tablet o un portátil cuando estamos fuera de casa, para poder navegar a través de estos dispositivos utilizando nuestra tarifa del móvil.");

